name: Playwright Testes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: 📦 Instalar dependências do projeto
      run: npm install

    - name: 📦 Instalando Playwright Navegadores
      run: npx playwright install --with-deps
      
    - name: 🧪 Rodando Playwright testes
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: 📑 Evidências dos Testes
        path: playwright-report/
        retention-days: 7